export const meetLinks=[
 {
  "index":"0",
  "route":"./devocional",
  "name":"Devocional",
  "iURL":"../images/cDevo.png"
 },
 {
  "index":"1",
  "route":"./kids",
  "name":"Niños",
  "iURL":"../images/cDevo.png"

 },
 {
  "index":"2",
  "route":"./young",
  "name":"Jóvenes",
  "iURL":"../images/cDevo.png"

 },
 {
  "index":"3",
  "route":"./prayer",
  "name":"Oración",
  "iURL":"../images/cDevo.png"
 },
 {
  "index":"4",
  "route":"./discipleship",
  "name":"Discipulado",
  "iURL":"../images/cDevo.png"
 },
 {
  "index":"5",
  "route":"./sunday",
  "name":"Dominical",
  "iURL":"../images/cDevo.png"
 }
];
